version: "3"

services:
  app:
    build: .
    container_name: app_test
    command: npm run dev
    environment:
      NODE_ENV: "test"
      DATABASE_ADDRESS: "mongodb"
      DATABASE_PORT: "27017"
      DATABASE_NAME: "dbapi"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
  mongodb:
    image: mongo
    container_name: mongodb_test
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    